"""get_documentation tool — serve Reducto SDK + REST documentation to agents.

Reads from mcp_server_reducto.docs_bundle (regenerated by /update-documentation skill).
Agents call this BEFORE writing Reducto code to get working SDK patterns for their
target platform — install commands, auth setup, code examples, response shapes.
"""

from __future__ import annotations

from typing import Literal

from mcp.server.fastmcp import Context
from mcp.types import CallToolResult, TextContent

from mcp_server_reducto.docs_bundle import DOCS
from mcp_server_reducto.errors import mcp_error
from mcp_server_reducto.server import mcp

VALID_TOPICS = sorted(DOCS.keys())
VALID_LANGUAGES = ["node", "python", "http"]


def _format_topic(topic: str, language: str | None) -> str:
    """Compose a markdown response for one topic, optionally narrowed to one language."""
    entry = DOCS[topic]
    parts: list[str] = []

    parts.append(f"# {topic}")
    parts.append("")
    parts.append(entry["summary"])
    parts.append("")

    if "endpoint" in entry:
        parts.append(f"**Endpoint:** `{entry['endpoint']}`")
        if entry.get("description"):
            parts.append("")
            parts.append(entry["description"])
        parts.append("")

    if language:
        # Single-language: code example + relevant field references
        if language not in entry.get("languages", {}):
            available = list(entry.get("languages", {}).keys())
            return f"# {topic}\n\nNo {language} content for this topic. Available: {available}"
        parts.append(entry["languages"][language])
        parts.append("")
    else:
        # All languages
        for lang in VALID_LANGUAGES:
            if lang in entry.get("languages", {}):
                parts.append(entry["languages"][lang])
                parts.append("")

    # Field references (from OpenAPI) — only when an endpoint is backing this topic
    if entry.get("request_fields"):
        parts.append("## Request fields")
        parts.append("")
        for name, desc in entry["request_fields"].items():
            parts.append(f"- `{name}` — {desc}")
        parts.append("")

    if entry.get("response_fields"):
        parts.append("## Response fields")
        parts.append("")
        for name, desc in entry["response_fields"].items():
            parts.append(f"- `{name}` — {desc}")
        parts.append("")

    return "\n".join(parts)


@mcp.tool(
    name="get_documentation",
    description=(
        "Get Reducto SDK and REST API documentation for a specific topic. "
        "Use this BEFORE writing Reducto integration code — it returns working code examples, "
        "install commands, auth setup, and response shapes for your target platform. "
        "Topics: " + ", ".join(VALID_TOPICS) + ". "
        "Languages: node, python, http (optional — omit to get all three). "
        "If you're unsure how to use any Reducto endpoint, call this tool first instead of "
        "guessing from training memory. The content is sourced from the live Reducto OpenAPI "
        "spec plus hand-curated SDK patterns including the Node SDK toFile() workaround, "
        "URLResult handling, form_schema caching for edits, and jobid:// chaining."
    ),
)
async def get_documentation(
    topic: Literal["quickstart", "parse", "extract", "split", "edit", "upload", "classify", "auth"],
    language: Literal["node", "python", "http"] | None = None,
    ctx: Context = None,  # type: ignore[assignment]
) -> CallToolResult:
    """Return docs for a topic, optionally narrowed to one language."""
    if topic not in DOCS:
        return mcp_error(
            f"Unknown topic: {topic!r}",
            guidance=f"Valid topics: {VALID_TOPICS}",
        )
    if language is not None and language not in VALID_LANGUAGES:
        return mcp_error(
            f"Unknown language: {language!r}",
            guidance=f"Valid languages: {VALID_LANGUAGES}, or omit for all three.",
        )

    text = _format_topic(topic, language)
    return CallToolResult(content=[TextContent(type="text", text=text)])
